package types

// InviteType : The type of an invite
type InviteType string

const (
	GROUP_InviteType  InviteType = "Group"
	SERVER_InviteType InviteType = "Server"
)

// Representation of an created invite on Revolt
type Invite struct {
	// The Id of the invite
	Id string `json:"_id,omitempty"`

	// The type of the invite
	Type InviteType `json:"type,omitempty"`

	// The creator of the invite
	Creator string `json:"creator,omitempty"`

	// The channel the invite is for
	Channel string `json:"channel,omitempty"`

	// The server the invite points to if it is a server invite
	Server string `json:"server,omitempty"`
}

type FullInvite struct {
	// The type of the invite
	Type InviteType `json:"type,omitempty"`

	// Invite code
	Code string `json:"code,omitempty"`

	// Id of the server
	ServerId string `json:"server_id,omitempty"`

	// Name of the server
	ServerName string `json:"server_name,omitempty"`

	// Representation of a File on Revolt Generated by Autumn
	//
	// <this is the icon of the server>
	ServerIcon *File `json:"server_icon,omitempty"`

	// Representation of a File on Revolt Generated by Autumn
	//
	// <this is the banner of the server>
	ServerBanner *File `json:"server_banner,omitempty"`

	// Enum of server flags
	ServerFlags int64 `json:"server_flags,omitempty"`

	// Id of server channel
	ChannelId string `json:"channel_id,omitempty"`

	// Name of server channel
	ChannelName string `json:"channel_name,omitempty"`

	// Description of server channel
	ChannelDescription string `json:"channel_description,omitempty"`

	// Name of user who created the invite
	Username string `json:"user_name,omitempty"`

	// Representation of a File on Revolt Generated by Autumn
	//
	// <this is the avatar of the user who created the invite>
	UserAvatar *File `json:"user_avatar,omitempty"`

	// Number of members in this server
	MemberCount int64 `json:"member_count,omitempty"`
}
